; This is the assembly code generated by GCC for correction_c.c
; It checks a multiplication table for correctness
	.file	"correction_c.c"
	.intel_syntax noprefix
	.text
	.data
	.align 32
; Multiplication table data: 9x9 table flattened into an array
.LC0:
	.long	7
	.long	2
	.long	3
	.long	4
	.long	5
	.long	6
	.long	7
	.long	8
	.long	9
	.long	2
	.long	4
	.long	7
	.long	8
	.long	10
	.long	12
	.long	14
	.long	16
	.long	18
	.long	3
	.long	6
	.long	9
	.long	12
	.long	15
	.long	18
	.long	21
	.long	24
	.long	27
	.long	4
	.long	8
	.long	12
	.long	16
	.long	7
	.long	24
	.long	28
	.long	32
	.long	36
	.long	5
	.long	10
	.long	15
	.long	20
	.long	25
	.long	30
	.long	35
	.long	40
	.long	45
	.long	6
	.long	12
	.long	18
	.long	24
	.long	30
	.long	7
	.long	42
	.long	48
	.long	54
	.long	7
	.long	14
	.long	21
	.long	28
	.long	35
	.long	42
	.long	49
	.long	56
	.long	63
	.long	8
	.long	16
	.long	24
	.long	32
	.long	40
	.long	48
	.long	56
	.long	7
	.long	72
	.long	9
	.long	18
	.long	27
	.long	36
	.long	45
	.long	54
	.long	63
	.long	72
	.long	81
	.text
; Main function entry point
	.globl	main
	.def	main;	.scl	2;	.type	32;	.endef
	.seh_proc	main
main:
	push	rbp
	.seh_pushreg	rbp
	push	rdi
	.seh_pushreg	rdi
	push	rsi
	.seh_pushreg	rsi
	sub	rsp, 368
	.seh_stackalloc	368
	lea	rbp, 128[rsp]
	.seh_setframe	rbp, 128
	.seh_endprologue
	call	__main ; Initialize C runtime
	lea	rax, -96[rbp] ; Address of local array on stack
	lea	rdx, .LC0[rip] ; Address of global data
	mov	ecx, 40 ; Number of quadwords to copy (160 bytes)
	mov	rdi, rax
	mov	rsi, rdx
	rep movsq ; Copy data to stack
	mov	rdx, rsi
	mov	rax, rdi
	mov	ecx, DWORD PTR [rdx]
	mov	DWORD PTR [rax], ecx
	lea	rax, -96[rbp] ; Pass array address to check_table
	mov	rcx, rax
	call	check_table ; Call the check function
	mov	eax, 0 ; Return 0
	add	rsp, 368
	pop	rsi
	pop	rdi
	pop	rbp
	ret
	.seh_endproc
	.section .rdata,"dr" ; Read-only data section
.LC1:
	.ascii "x y\0" ; String: "x y"
.LC2:
	.ascii "%d  %d      error\12\0" ; Format string for error message
.LC3:
	.ascii "accomplish!\0" ; Success message
	.text
; Check table function
	.globl	check_table
	.def	check_table;	.scl	2;	.type	32;	.endef
	.seh_proc	check_table
check_table:
	push	rbp
	.seh_pushreg	rbp
	mov	rbp, rsp
	.seh_setframe	rbp, 0
	sub	rsp, 48
	.seh_stackalloc	48
	.seh_endprologue
	mov	QWORD PTR 16[rbp], rcx ; Save array pointer parameter
	lea	rax, .LC1[rip]
	mov	rcx, rax
	call	puts ; Print "x y"
	mov	DWORD PTR -4[rbp], 0 ; i = 0 (outer loop)
	jmp	.L4
.L8:
	mov	DWORD PTR -8[rbp], 0 ; j = 0 (inner loop)
	jmp	.L5
.L7:
	; Calculate expected value: (i+1) * (j+1)
	mov	eax, DWORD PTR -4[rbp]
	lea	edx, 1[rax] ; i+1
	mov	eax, DWORD PTR -8[rbp]
	add	eax, 1 ; j+1
	imul	eax, edx ; expected = (i+1)*(j+1)
	mov	DWORD PTR -12[rbp], eax
	; Calculate array index: i*9 + j
	mov	eax, DWORD PTR -4[rbp]
	movsx	rdx, eax
	mov	rax, rdx
	sal	rax, 3 ; *8
	add	rax, rdx ; *9
	sal	rax, 2 ; *36 (since 9*4=36 bytes per row)
	mov	rdx, rax
	mov	rax, QWORD PTR 16[rbp] ; base address
	add	rdx, rax ; address of table[i*9 + j]
	mov	eax, DWORD PTR -8[rbp]
	cdqe
	mov	eax, DWORD PTR [rdx+rax*4] ; actual value
	cmp	DWORD PTR -12[rbp], eax ; compare expected and actual
	je	.L6 ; if equal, skip error
	; Print error message
	mov	eax, DWORD PTR -8[rbp]
	lea	edx, 1[rax] ; j+1
	mov	eax, DWORD PTR -4[rbp]
	add	eax, 1 ; i+1
	mov	r8d, edx
	mov	edx, eax
	lea	rax, .LC2[rip]
	mov	rcx, rax
	call	printf ; printf("%d  %d      error\n", i+1, j+1)
.L6:
	add	DWORD PTR -8[rbp], 1 ; j++
.L5:
	cmp	DWORD PTR -8[rbp], 8 ; j <= 8
	jle	.L7
	add	DWORD PTR -4[rbp], 1 ; i++
.L4:
	cmp	DWORD PTR -4[rbp], 8 ; i <= 8
	jle	.L8
	lea	rax, .LC3[rip]
	mov	rcx, rax
	call	puts ; Print "accomplish!"
	nop
	add	rsp, 48
	pop	rbp
	ret
	.seh_endproc
	.def	__main;	.scl	2;	.type	32;	.endef
	.ident	"GCC: (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r3) 14.2.0"
	.def	puts;	.scl	2;	.type	32;	.endef
	.def	printf;	.scl	2;	.type	32;	.endef
; End of assembly file
